"""Parse pyproject.toml and emit a raw inventory of every declared dependency.

This is the source-of-truth pass for w1 of the dependency audit. We deliberately
parse pyproject.toml directly rather than `uv pip list` because the latter
includes transitive packages, which would mask which extras group owns a dep.
"""

from __future__ import annotations

import pathlib
import re
import sys
import tomllib
from collections import defaultdict


def split_spec(spec: str) -> tuple[str, str, str]:
    """Return (name, version_spec, env_marker) from a PEP 508 requirement string."""
    s = spec.strip()
    marker = ""
    if ";" in s:
        body, marker = s.split(";", 1)
        body = body.strip()
        marker = marker.strip()
    else:
        body = s
    # Strip extras: pkg[extra1,extra2]
    extras = ""
    m = re.match(r"^([A-Za-z0-9_.\-]+)(\[[^\]]+\])?(.*)$", body)
    if not m:
        return body.lower(), "", marker
    name = m.group(1).lower()
    extras = m.group(2) or ""
    rest = m.group(3).strip()
    version = rest
    full_name = name + extras
    return full_name, version, marker


def main() -> int:
    root = pathlib.Path(__file__).resolve().parents[2]
    pyproject = root / "pyproject.toml"
    out = root / "docs/development/dependency-audit-raw.md"
    data = tomllib.loads(pyproject.read_text(encoding="utf-8"))

    # name (with extras suffix) -> {(group, version, marker)}
    table: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    bare_name: dict[str, str] = {}  # canonical name without extras

    project = data.get("project", {})
    for s in project.get("dependencies", []):
        n, v, m = split_spec(s)
        table[n].append(("core", v, m))
    for grp, items in project.get("optional-dependencies", {}).items():
        for s in items:
            n, v, m = split_spec(s)
            table[n].append((f"extras:{grp}", v, m))
    for grp, items in data.get("dependency-groups", {}).items():
        for s in items:
            if isinstance(s, str):
                n, v, m = split_spec(s)
                table[n].append((f"dep-group:{grp}", v, m))

    sources = data.get("tool", {}).get("uv", {}).get("sources", {})

    # Generate markdown
    lines = []
    lines.append("# Dependency Audit — Raw Inventory\n")
    lines.append(
        "Generated by `_project/scratch/parse_deps.py` from `pyproject.toml`. "
        "This is the w1 deliverable for the `audit-imported-dependencies-for-elimination` TODO. "
        "It enumerates every dep declared in the manifest. Transitive deps are NOT listed here; "
        "see `uv tree` for those.\n"
    )
    lines.append(f"\n**Source manifest:** `{pyproject.relative_to(root)}`  ")
    lines.append(f"**Distinct declared package names:** {len({k.split('[')[0] for k in table})}  ")
    lines.append(f"**Total declarations (incl. duplicates across groups):** {sum(len(v) for v in table.values())}\n")

    lines.append("\n## Declared Packages\n")
    lines.append("| Package | Version Spec | Groups | Markers / Notes |")
    lines.append("| --- | --- | --- | --- |")
    for name in sorted(table):
        rows = table[name]
        # Collect distinct version specs and group lists
        groups = sorted({r[0] for r in rows})
        version_specs = sorted({r[1] for r in rows if r[1]})
        markers = sorted({r[2] for r in rows if r[2]})
        notes = []
        if name in sources:
            notes.append(f"uv.source: `{sources[name]}`")
        if markers:
            notes.append("; ".join(markers))
        version_cell = " / ".join(f"`{v}`" for v in version_specs) if version_specs else "—"
        groups_cell = ", ".join(f"`{g}`" for g in groups)
        notes_cell = "<br>".join(notes) if notes else ""
        lines.append(f"| `{name}` | {version_cell} | {groups_cell} | {notes_cell} |")

    if sources:
        lines.append("\n## `[tool.uv.sources]` Overrides\n")
        lines.append("| Package | Source |")
        lines.append("| --- | --- |")
        for k, v in sorted(sources.items()):
            lines.append(f"| `{k}` | `{v}` |")

    # Group composition table
    lines.append("\n## Group Composition (by extras / dep-group)\n")
    grp_to_pkgs: dict[str, list[str]] = defaultdict(list)
    for name, rows in table.items():
        for g, _, _ in rows:
            grp_to_pkgs[g].append(name)
    lines.append("| Group | Packages |")
    lines.append("| --- | --- |")
    for g in sorted(grp_to_pkgs):
        pkgs = sorted(set(grp_to_pkgs[g]))
        lines.append(f"| `{g}` | " + ", ".join(f"`{p}`" for p in pkgs) + " |")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out.relative_to(root)} — {len(table)} declared packages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
