from __future__ import annotations

import argparse
import pathlib
import re
import sys
import tomllib
from collections import defaultdict

_HERE = pathlib.Path(__file__).resolve().parent
_ROOT = _HERE.parents[2]
_OUT_REL = "docs/development/dependency-audit-raw.md"
_GENERATOR_REL = "_project/scripts/dependency_audit/parse_deps.py"


CLI_EPILOG = (
    "Parse pyproject.toml and emit a raw inventory of every declared dependency.\n"
    "\n"
    "This is the source-of-truth pass for w1 of the dependency audit. We deliberately\n"
    "parse pyproject.toml directly rather than `uv pip list` because the latter\n"
    "includes transitive packages, which would mask which extras group owns a dep.\n"
    "\n"
    "Usage:\n"
    "    uv run -- python _project/scripts/dependency_audit/parse_deps.py            # write docs\n"
    "    uv run -- python _project/scripts/dependency_audit/parse_deps.py --check    # drift gate\n"
    "\n"
    "Exit codes:\n"
    "    0  Doc written (default) or already up to date (--check).\n"
    "    1  --check found drift between the committed doc and the manifest.\n"
)


def split_spec(spec: str) -> tuple[str, str, str]:
    s = spec.strip()
    marker = ""
    if ";" in s:
        body, marker = s.split(";", 1)
        body = body.strip()
        marker = marker.strip()
    else:
        body = s
    extras = ""
    m = re.match(r"^([A-Za-z0-9_.\-]+)(\[[^\]]+\])?(.*)$", body)
    if not m:
        return body.lower(), "", marker
    name = m.group(1).lower()
    extras = m.group(2) or ""
    rest = m.group(3).strip()
    version = rest
    full_name = name + extras
    return full_name, version, marker


def render(root: pathlib.Path) -> str:
    pyproject = root / "pyproject.toml"
    data = tomllib.loads(pyproject.read_text(encoding="utf-8"))

    table: dict[str, list[tuple[str, str, str]]] = defaultdict(list)

    project = data.get("project", {})
    for s in project.get("dependencies", []):
        n, v, m = split_spec(s)
        table[n].append(("core", v, m))
    for grp, items in project.get("optional-dependencies", {}).items():
        for s in items:
            n, v, m = split_spec(s)
            table[n].append((f"extras:{grp}", v, m))
    for grp, items in data.get("dependency-groups", {}).items():
        for s in items:
            if isinstance(s, str):
                n, v, m = split_spec(s)
                table[n].append((f"dep-group:{grp}", v, m))

    sources = data.get("tool", {}).get("uv", {}).get("sources", {})

    lines = []
    lines.append("# Dependency Audit - Raw Inventory\n")
    lines.append(
        f"Generated by `{_GENERATOR_REL}` from `pyproject.toml`. "
        "This is the w1 deliverable for the `audit-imported-dependencies-for-elimination` TODO. "
        "It enumerates every dep declared in the manifest. Transitive deps are NOT listed here; "
        "see `uv tree` for those.\n"
    )
    lines.append("")
    lines.append(f"- **Source manifest:** `{pyproject.relative_to(root)}`")
    lines.append(f"- **Distinct declared package names:** {len({k.split('[')[0] for k in table})}")
    lines.append(f"- **Total declarations (incl. duplicates across groups):** {sum(len(v) for v in table.values())}")

    lines.append("\n## Declared Packages\n")
    lines.append("| Package | Version Spec | Groups | Markers / Notes |")
    lines.append("| --- | --- | --- | --- |")
    for name in sorted(table):
        rows = table[name]
        groups = sorted({r[0] for r in rows})
        version_specs = sorted({r[1] for r in rows if r[1]})
        markers = sorted({r[2] for r in rows if r[2]})
        notes = []
        if name in sources:
            notes.append(f"uv.source: `{sources[name]}`")
        if markers:
            notes.append("; ".join(markers))
        version_cell = " / ".join(f"`{v}`" for v in version_specs) if version_specs else "-"
        groups_cell = ", ".join(f"`{g}`" for g in groups)
        notes_cell = "<br>".join(notes) if notes else ""
        lines.append(f"| `{name}` | {version_cell} | {groups_cell} | {notes_cell} |")

    if sources:
        lines.append("\n## `[tool.uv.sources]` Overrides\n")
        lines.append("| Package | Source |")
        lines.append("| --- | --- |")
        for k, v in sorted(sources.items()):
            lines.append(f"| `{k}` | `{v}` |")

    lines.append("\n## Group Composition (by extras / dep-group)\n")
    grp_to_pkgs: dict[str, list[str]] = defaultdict(list)
    for name, rows in table.items():
        for g, _, _ in rows:
            grp_to_pkgs[g].append(name)
    lines.append("| Group | Packages |")
    lines.append("| --- | --- |")
    for g in sorted(grp_to_pkgs):
        pkgs = sorted(set(grp_to_pkgs[g]))
        lines.append(f"| `{g}` | " + ", ".join(f"`{p}`" for p in pkgs) + " |")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Parse pyproject.toml into docs/development/dependency-audit-raw.md.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=CLI_EPILOG,
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the committed doc matches the manifest; exit non-zero on drift (no write).",
    )
    args = parser.parse_args()

    out = _ROOT / _OUT_REL
    content = render(_ROOT)

    if args.check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != content:
            print(
                f"DRIFT: {out.relative_to(_ROOT)} is out of date with pyproject.toml.\n"
                f"Regenerate it with: uv run -- python {_GENERATOR_REL}\n"
                "(or `make guards-fix` to regenerate every mechanical drift-guard artifact)",
                file=sys.stderr,
            )
            return 1
        print(f"{out.relative_to(_ROOT)} is up to date")
        return 0

    out.write_text(content, encoding="utf-8")
    print(f"wrote {out.relative_to(_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
