CREATE TABLE IF NOT EXISTS metadata (
    read_model_version INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS result_environment (
    result_id        VARCHAR PRIMARY KEY,
    os               VARCHAR,
    arch             VARCHAR,
    cpu_count        INTEGER,
    memory_gb        DOUBLE,
    python           VARCHAR,
    cpu_model        VARCHAR,
    cpu_family       VARCHAR,
    cpu_identity_provenance VARCHAR,
    client_region    VARCHAR,
    client_cloud     VARCHAR,
    statement_overhead_min_ms DOUBLE,
    statement_overhead_median_ms DOUBLE,
    link_status      VARCHAR
);

CREATE TABLE IF NOT EXISTS result_phase_durations (
    result_id        VARCHAR NOT NULL,
    phase            VARCHAR NOT NULL,
    duration_s       DOUBLE  NOT NULL,
    PRIMARY KEY (result_id, phase)
);

CREATE TABLE IF NOT EXISTS result_basis_availability (
    result_id               VARCHAR PRIMARY KEY,
    has_warmup              BOOLEAN NOT NULL,
    measurement_pass_count  INTEGER NOT NULL,
    warmup_status           VARCHAR NOT NULL,
    available_bases         VARCHAR NOT NULL,
    varying_pass_queries    VARCHAR
);

CREATE TABLE IF NOT EXISTS results (
    result_id            VARCHAR  PRIMARY KEY,
    benchmark            VARCHAR  NOT NULL,
    scale_factor         DOUBLE   NOT NULL,
    platform             VARCHAR  NOT NULL,
    platform_id          VARCHAR  NOT NULL,
    driver_version       VARCHAR,
    run_date             VARCHAR  NOT NULL,
    power_score          DOUBLE,
    total_duration_s     DOUBLE   NOT NULL,
    geomean_ms           DOUBLE,
    display_geomean_ms   DOUBLE,
    query_count          INTEGER  NOT NULL,
    logical_query_count  INTEGER  NOT NULL,
    has_display_timing   BOOLEAN  NOT NULL,
    valid_query_count    INTEGER  NOT NULL,
    missing_query_count  INTEGER  NOT NULL,
    zero_timing_count    INTEGER  NOT NULL,
    display_exclusion_reason    VARCHAR,
    comparison_exclusion_reason VARCHAR,
    ranking_exclusion_reason    VARCHAR,
    trust_label          VARCHAR  NOT NULL,
    visibility           VARCHAR  NOT NULL,
    funding              VARCHAR  NOT NULL,
    platform_version     VARCHAR,
    execution_mode       VARCHAR,
    tuning_mode          VARCHAR,
    tuning_hash          VARCHAR,
    requested_config_hash VARCHAR,
    applied_ledger_hash   VARCHAR,
    tuning_validation_status VARCHAR,
    applied_receipt      VARCHAR,
    override_rules       VARCHAR,
    override_evidence    VARCHAR,
    override_approver    VARCHAR,
    override_expires     VARCHAR,
    tuning_policy_generation VARCHAR,
    test_type            VARCHAR,
    validation_status    VARCHAR,
    cost_usd             DOUBLE,
    normalized_cost_usd  DOUBLE,
    cost_model_version   VARCHAR,
    cost_model_source    VARCHAR,
    cost_scope           VARCHAR,
    cost_status          VARCHAR  NOT NULL,
    billing_unit         VARCHAR,
    pricing_region       VARCHAR,
    deployment_class     VARCHAR,
    cloud_provider       VARCHAR,
    cloud_region         VARCHAR,
    instance_or_warehouse VARCHAR,
    storage_format       VARCHAR,
    instance_type        VARCHAR,
    warehouse_size       VARCHAR,
    node_count           INTEGER,
    cluster_size         VARCHAR,
    storage_tier         VARCHAR,
    compliance_class     VARCHAR,
    is_ranking_eligible  BOOLEAN  NOT NULL,
    has_plans            BOOLEAN  NOT NULL,
    plans_published      BOOLEAN  NOT NULL,
    has_tuning           BOOLEAN  NOT NULL,
    bundle_download_url  VARCHAR  NOT NULL,
    physical_mechanisms   VARCHAR,
    physical_rendering_id VARCHAR,
    benchmark_support_status VARCHAR,
    throughput_at_size   DOUBLE,
    stream_count         INTEGER
);

CREATE TABLE IF NOT EXISTS query_display_timings (
    result_id    VARCHAR  NOT NULL,
    query_id     VARCHAR  NOT NULL,
    display_ms   DOUBLE,
    sample_count INTEGER  NOT NULL,
    is_valid_display_timing BOOLEAN NOT NULL,
    timing_exclusion_reason VARCHAR,
    PRIMARY KEY (result_id, query_id)
);

CREATE TABLE IF NOT EXISTS query_executions (
    result_id    VARCHAR  NOT NULL,
    query_id     VARCHAR  NOT NULL,
    duration_ms  DOUBLE   NOT NULL,
    status       VARCHAR  NOT NULL,
    run_type     VARCHAR,
    iter         INTEGER,
    stream       INTEGER
);

CREATE INDEX IF NOT EXISTS idx_query_executions_result
    ON query_executions (result_id);

CREATE VIEW IF NOT EXISTS result_detail_metrics AS
SELECT
    r.result_id,
    r.benchmark,
    r.scale_factor,
    r.platform,
    r.platform_id,
    r.driver_version,
    r.run_date,
    r.power_score,
    r.total_duration_s,
    r.geomean_ms,
    r.display_geomean_ms,
    r.query_count,
    r.logical_query_count,
    r.has_display_timing,
    r.valid_query_count,
    r.missing_query_count,
    r.zero_timing_count,
    r.display_exclusion_reason,
    r.comparison_exclusion_reason,
    r.ranking_exclusion_reason,
    r.trust_label,
    r.visibility,
    r.funding,
    r.platform_version,
    r.execution_mode,
    r.tuning_mode,
    r.tuning_hash,
    r.requested_config_hash,
    r.applied_ledger_hash,
    r.tuning_validation_status,
    r.applied_receipt,
    r.override_rules,
    r.override_evidence,
    r.override_approver,
    r.override_expires,
    r.tuning_policy_generation,
    r.test_type,
    r.validation_status,
    r.cost_usd,
    r.normalized_cost_usd,
    r.cost_model_version,
    r.cost_model_source,
    r.cost_scope,
    r.cost_status,
    r.billing_unit,
    r.pricing_region,
    r.deployment_class,
    r.cloud_provider,
    r.cloud_region,
    r.instance_or_warehouse,
    r.instance_type,
    r.warehouse_size,
    r.node_count,
    r.cluster_size,
    r.storage_format,
    r.storage_tier,
    r.compliance_class,
    r.has_plans,
    r.plans_published,
    r.has_tuning,
    r.bundle_download_url,
    r.physical_mechanisms,
    r.physical_rendering_id,
    r.benchmark_support_status,
    r.throughput_at_size,
    r.stream_count,
    e.os,
    e.arch,
    e.cpu_count,
    e.memory_gb,
    e.python,
    e.cpu_model,
    e.cpu_family,
    e.cpu_identity_provenance,
    e.client_region,
    e.client_cloud,
    e.statement_overhead_min_ms,
    e.statement_overhead_median_ms,
    e.link_status
FROM results r
LEFT JOIN result_environment e USING (result_id);

CREATE TABLE IF NOT EXISTS benchmark_matrix_cells (
    benchmark    VARCHAR  NOT NULL,
    scale_factor DOUBLE   NOT NULL,
    phase        VARCHAR  NOT NULL,
    result_id    VARCHAR  NOT NULL,
    platform_id  VARCHAR  NOT NULL,
    query_id     VARCHAR  NOT NULL,
    display_ms   DOUBLE,
    is_valid_display_timing BOOLEAN NOT NULL,
    timing_exclusion_reason VARCHAR,
    stream_count INTEGER,
    PRIMARY KEY (benchmark, scale_factor, phase, result_id, query_id)
);

CREATE INDEX IF NOT EXISTS idx_matrix_cells_cohort
    ON benchmark_matrix_cells (benchmark, scale_factor, phase);

CREATE TABLE IF NOT EXISTS benchmark_rankings (
    benchmark          VARCHAR  NOT NULL,
    scale_factor       DOUBLE   NOT NULL,
    phase              VARCHAR  NOT NULL,
    result_id          VARCHAR  NOT NULL,
    platform_id        VARCHAR  NOT NULL,
    platform           VARCHAR  NOT NULL,
    short_id           VARCHAR  NOT NULL,
    trust_label        VARCHAR  NOT NULL,
    funding            VARCHAR  NOT NULL,
    tuning_mode        VARCHAR,
    tuning_hash        VARCHAR,
    execution_mode     VARCHAR,
    compliance_class   VARCHAR,
    run_date           VARCHAR  NOT NULL,
    is_ranking_eligible BOOLEAN NOT NULL,
    has_display_timing BOOLEAN  NOT NULL,
    logical_query_count INTEGER NOT NULL,
    valid_query_count  INTEGER  NOT NULL,
    missing_query_count INTEGER NOT NULL,
    zero_timing_count  INTEGER  NOT NULL,
    display_exclusion_reason    VARCHAR,
    comparison_exclusion_reason VARCHAR,
    ranking_exclusion_reason    VARCHAR,
    power_score        DOUBLE,
    display_geomean_ms DOUBLE,
    sample_geomean_ms  DOUBLE,
    cost_usd           DOUBLE,
    primary_metric     VARCHAR  NOT NULL,
    primary_order      VARCHAR  NOT NULL,
    rank               INTEGER,
    total_in_cohort    INTEGER  NOT NULL,
    cohort_ranked_count INTEGER NOT NULL,
    cohort_ranking_exclusion_reason VARCHAR,
    percentile_p50     DOUBLE,
    percentile_p90     DOUBLE,
    percentile_p95     DOUBLE,
    percentile_p99     DOUBLE,
    speedup_vs_best              DOUBLE,
    speedup_vs_slowest_in_cohort DOUBLE,
    throughput_at_size           DOUBLE,
    stream_count                 INTEGER,
    PRIMARY KEY (benchmark, scale_factor, phase, result_id)
);

CREATE INDEX IF NOT EXISTS idx_benchmark_rankings_cohort
    ON benchmark_rankings (benchmark, scale_factor, phase);

CREATE VIEW IF NOT EXISTS platform_index_rows AS
SELECT
    result_id,
    benchmark,
    scale_factor,
    platform,
    platform_id,
    driver_version,
    run_date,
    power_score,
    total_duration_s,
    geomean_ms,
    display_geomean_ms,
    query_count,
    logical_query_count,
    has_display_timing,
    valid_query_count,
    missing_query_count,
    zero_timing_count,
    display_exclusion_reason,
    comparison_exclusion_reason,
    ranking_exclusion_reason,
    trust_label,
    funding,
    tuning_mode,
    execution_mode,
    compliance_class,
    cost_usd,
    normalized_cost_usd,
    cost_model_version,
    cost_model_source,
    cost_scope,
    cost_status,
    billing_unit,
    pricing_region,
    deployment_class,
    cloud_provider,
    cloud_region,
    instance_or_warehouse,
    instance_type,
    warehouse_size,
    node_count,
    cluster_size,
    storage_format,
    storage_tier
FROM results;

CREATE TABLE IF NOT EXISTS cohort_metadata (
    cohort_key     VARCHAR  NOT NULL,
    benchmark      VARCHAR  NOT NULL,
    scale_factor   DOUBLE   NOT NULL,
    phase          VARCHAR  NOT NULL,
    cohort_label   VARCHAR  NOT NULL,
    cohort_href    VARCHAR  NOT NULL,
    platform_count INTEGER  NOT NULL,
    cohort_ranked_count INTEGER NOT NULL,
    cohort_ranking_exclusion_reason VARCHAR,
    primary_metric VARCHAR  NOT NULL,
    primary_order  VARCHAR  NOT NULL,
    platform_id    VARCHAR  NOT NULL,
    platform       VARCHAR  NOT NULL,
    result_id      VARCHAR  NOT NULL,
    short_id       VARCHAR  NOT NULL,
    tuning_mode    VARCHAR,
    trust_label    VARCHAR  NOT NULL,
    has_display_timing BOOLEAN NOT NULL,
    logical_query_count INTEGER NOT NULL,
    valid_query_count INTEGER NOT NULL,
    missing_query_count INTEGER NOT NULL,
    zero_timing_count INTEGER NOT NULL,
    display_exclusion_reason VARCHAR,
    comparison_exclusion_reason VARCHAR,
    ranking_exclusion_reason VARCHAR,
    rank           INTEGER,
    metric_value   DOUBLE,
    speedup_vs_best DOUBLE,
    stream_count   INTEGER,
    PRIMARY KEY (cohort_key, result_id)
);

CREATE INDEX IF NOT EXISTS idx_cohort_metadata_key
    ON cohort_metadata (cohort_key);

CREATE INDEX IF NOT EXISTS idx_cohort_metadata_platform
    ON cohort_metadata (cohort_key, platform_id);

CREATE TABLE IF NOT EXISTS meta_leaderboard (
    platform_id  VARCHAR  PRIMARY KEY,
    platform     VARCHAR  NOT NULL,
    avg_rank     DOUBLE,
    n_cohorts    INTEGER  NOT NULL
);

CREATE TABLE IF NOT EXISTS short_ids (
    short_id   VARCHAR  PRIMARY KEY,
    result_id  VARCHAR  NOT NULL UNIQUE
);
