"""Runtime contracts for core benchmark/lifecycle integration."""

from benchbox.core.contracts.benchmark_runtime import (
    EXTENDED_RUNTIME_METHODS,
    REQUIRED_RUNTIME_METHODS,
    BenchmarkExtendedRuntimeContract,
    BenchmarkRuntimeContract,
    get_missing_methods,
    has_extended_runtime_contract,
    has_runtime_contract,
)
from benchbox.core.contracts.platform_capabilities import (
    CapabilityContractError,
    CategorizedQueryBenchmark,
    ConnectionFactory,
    ConnectionLifecycle,
    DataFrameBenchmarkExecutor,
    DataFrameQueryRuntime,
    ExternalTableLoader,
    NativeTableLoader,
    PlanCaptureRuntime,
    SQLBenchmarkExecutor,
    StatisticsPhaseRunner,
    TuningLedgerWriter,
)
from benchbox.core.contracts.platform_capability_views import (
    as_connection_factory,
    as_connection_lifecycle,
    as_dataframe_benchmark_executor,
    as_dataframe_query_runtime,
    as_external_table_loader,
    as_native_table_loader,
    as_plan_capture_runtime,
    as_sql_benchmark_executor,
    as_statistics_phase_runner,
    as_tuning_ledger_writer,
    run_categorized_query_benchmark,
)

__all__ = [
    "BenchmarkRuntimeContract",
    "BenchmarkExtendedRuntimeContract",
    "REQUIRED_RUNTIME_METHODS",
    "EXTENDED_RUNTIME_METHODS",
    "get_missing_methods",
    "has_runtime_contract",
    "has_extended_runtime_contract",
    "CapabilityContractError",
    "CategorizedQueryBenchmark",
    "ConnectionFactory",
    "ConnectionLifecycle",
    "DataFrameBenchmarkExecutor",
    "DataFrameQueryRuntime",
    "ExternalTableLoader",
    "NativeTableLoader",
    "PlanCaptureRuntime",
    "SQLBenchmarkExecutor",
    "StatisticsPhaseRunner",
    "TuningLedgerWriter",
    "as_connection_factory",
    "as_connection_lifecycle",
    "as_dataframe_benchmark_executor",
    "as_dataframe_query_runtime",
    "as_external_table_loader",
    "as_native_table_loader",
    "as_plan_capture_runtime",
    "as_sql_benchmark_executor",
    "as_statistics_phase_runner",
    "as_tuning_ledger_writer",
    "run_categorized_query_benchmark",
]
